# Generated by Django 4.0.4 on 2022-05-14 21:41

import django.core.validators
from django.db import migrations, models
import links.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_address",
                    models.URLField(
                        unique=True, validators=[django.core.validators.URLValidator]
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=links.utils.get_unique_key, max_length=255, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
