name: Omni Test

on:
  push:
    branches:
      - main

env:
  DATABASE_URL: postgres://omni:omni@localhost:5432/omni

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:10.8
        env:
          POSTGRES_USER: omni
          POSTGRES_PASSWORD: omni
          POSTGRES_DB: omni
          PGDATA: /var/lib/postgresql/data/pgdata
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        working-directory: ./backend
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Check linting with flake8
        working-directory: ./backend
        run: |
          flake8

      - name: Test with pytest and display coverage
        working-directory: ./backend
        run: |
          pytest
